import { useState, useEffect, useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// Import global context
import { DataContext } from "../store/GlobalState";

import { Product } from "../Components/Products/Product";

export default function Home() {
  const { state, dispatch } = useContext(DataContext);
  console.log("STATE: ", state);

  // Handle adding product to cart
  const handleAddToCart = () => {
    console.log("Add");
  };

  const renderProducts = () => {
    return state.products.map((product, i) => {
      return <Product key={i} product={product} />;
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.productContainer}>{renderProducts()}</div>
    </div>
  );
}
