import { useState, useEffect, useContext } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// Import global context
import { DataContext } from "../store/GlobalState";
import { addToCart } from "../store/Actions";

import { Product } from "../Components/Products/Product";

export default function Home() {
  const { state, dispatch } = useContext(DataContext);
  const router = useRouter();
  const { cart, products } = state;
  console.log("STATE: ", state);

  // Handle the click of the product box and add to cart button
  const handleProductClick = (product, e) => {
    if (e.target.id === "add_btn") {
      // Handle button click
      console.log("BUTTON CLICKED", product.id);
      // Dispatch add cart
      dispatch(addToCart(product, cart));
    } else {
      router.push(`/product/${product.id}`);
    }
  };

  // Render product items
  const renderProducts = () => {
    return products.map((product, i) => {
      return (
        <Product
          key={i}
          product={product}
          handleProductClick={handleProductClick}
        />
      );
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.productContainer}>Products{renderProducts()}</div>
    </div>
  );
}
